on: [push]
name: Linux_Container_Workflow 

jobs:
  build-and-deploy-client:
    runs-on: ubuntu-latest
    steps:

    - name: 'checkout the repo'
      uses: actions/checkout@v2

    - name: 'Login to Azure'
      uses: azure/login@v1.1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Login to Container Registry
      uses: docker/login-action@v1
      with:
        registry: identityserveracr2.azurecr.io
        username: IdentityServerACR2
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: 'Build and push to registry'
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        file: ./Dockerfile_client
        push: true
        tags: identityserveracr2.azurecr.io/${{ secrets.USERNAME }}-client:${{ github.sha }}

        
    - name: 'Deploy to Azure Container Instances'
      uses: 'azure/aci-deploy@v1'
      with:
        resource-group: 'IdentityServerCourse'
        dns-name-label: ${{ secrets.USERNAME }}-client
        image: identityserveracr2.azurecr.io/${{ secrets.USERNAME }}-client:${{ github.sha }}
        registry-login-server: identityserveracr2.azurecr.io
        registry-username: IdentityServerACR2
        registry-password: ${{ secrets.REGISTRY_PASSWORD }}
        name: ${{ secrets.USERNAME }}-client
        ports: 80 443
        cpu: 0.5
        memory: 0.5
        location: 'northeurope'
        environment-variables: ASPNETCORE_ENVIRONMENT=Production GITHUB__SHA=${{ github.sha }}

